### PR TITLE
fix currentPreview from searchFragment

### LINKED ISSUE #389: Fix preview from searchFragment
[Sentry link](https://sentry.infomaniak.com/organizations/infomaniak/issues/1868/?project=3)

No current preview found

### PR DESCRIPTION
**Pull request by sirambd**
Fix: 
- Fix old filter view on previous from preview
- [Sentry link](https://sentry.infomaniak.com/organizations/infomaniak/issues/1868/?project=3)

```
java.lang.Exception: No current preview found
    at com.infomaniak.drive.ui.fileList.preview.PreviewSliderFragment.onViewCreated(PreviewSliderFragment.kt:85)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

closes #389 

Signed-off-by: Abdourahamane BOINAIDI <abdourahamane.boinaidi@infomaniak.com>

### CODE REVIEW

**Review by KevinBoulongne — APPROVED** [review]

File: app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt [hunk 1]
```diff
@@ -214,7 +225,7 @@ class SearchFragment : FileListFragment() {
 
             val oldList = fileListViewModel.oldList?.toMutableList() as? ArrayList
```
Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt:226]: Now the oldList becomes useless

Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt:226]: Now the oldList becomes useless

**Review by JorisBodin — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt (hunk 1 above)
Comment (sirambd) [reply app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt]: Now it is used, to avoid another type of bug that can arise

**Review by JorisBodin — APPROVED** [review]
