### PR TITLE
Fixed CreateCategory rights issue in SelectedCategories screen

### LINKED ISSUE #468: We can create a new Category even if we don't have the rights to do it

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #468

### CODE REVIEW

**Review by JorisBodin — APPROVED** [review]

File: app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt [hunk 1]
```diff
@@ -78,11 +78,11 @@ class CategoryInfoActionsBottomSheetDialog : BottomSheetDialogFragment() {
...
-        (rights?.canEditCategory ?: false).let {
+        rights.canEditCategory.let {
             disabledEditCategory.isGone = it
             editCategory.isEnabled = it
         }
-        (rights?.canDeleteCategory ?: false && !navigationArgs.categoryIsPredefined).let {
+        (rights.canDeleteCategory && !navigationArgs.categoryIsPredefined).let {
             disabledDeleteCategory.isGone = it
             deleteCategory.isEnabled = it
         }
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt:88]: I suggest this 

```kotlin
    private fun handleRights() = with(DriveInfosController.getCategoryRights()) {
        disabledEditCategory.isGone = canEditCategory
        editCategory.isEnabled = canEditCategory

        with(canDeleteCategory && !navigationArgs.categoryIsPredefined) {
            disabledDeleteCategory.isGone = this
            deleteCategory.isEnabled = this
        }
    }
```

File: app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt [hunk 2]
```diff
@@ -73,7 +73,7 @@ class SearchFiltersFragment : Fragment() {
     }
 
     private fun handleCategoryRights() {
-        val isVisible = categoryRights?.canReadCategoryOnFile == true
+        val isVisible = categoryRights.canReadCategoryOnFile
         categoriesTitle.isVisible = isVisible
         chooseCategoriesFilter.isVisible = isVisible
     }
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt:79]: You can also do it like this

```kotlin
    private fun handleCategoryRights() = with(categoryRights.canReadCategoryOnFile) {
        categoriesTitle.isVisible = this
        chooseCategoriesFilter.isVisible = this
    }
```

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt [hunk 3]
```diff
@@ -80,17 +80,15 @@ class SelectCategoriesFragment : Fragment() {
             }
         }
 
-        (if (usageMode == SELECTED_CATEGORIES) CategoryRights() else DriveInfosController.getCategoryRights()).let {
-            setCategoriesAdapter(it?.canEditCategory == true, it?.canDeleteCategory == true)
-            setAddCategoryButton(it?.canCreateCategory == true)
+        (if (usageMode == MANAGED_CATEGORIES) DriveInfosController.getCategoryRights() else CategoryRights()).let {
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt:83]: Need refactor, and not need let here

**Review by sirambd — APPROVED** [review]
