### PR TITLE
Fixed icons tint

### LINKED ISSUE #499: File icon is blinking in FileDetailsFragment

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #499

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/utils/Extensions.kt [hunk 1]
```diff
@@ -832,22 +838,22 @@ fun MaterialCardView.setCornersRadius(topCornerRadius: Float, bottomCornerRadius
  * This is not the only method in this case, search this comment in the project, and you'll see.
  * Realm's Github issue: https://github.com/realm/realm-java/issues/7637
  */
-fun File.getFolderIcon(context: Context): Drawable? {
+fun File.getFolderIcon(): Pair<Int?, String?> {
     return if (isFolder()) {
```
Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/utils/Extensions.kt:842]: The isFolder() is not necessary

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt [hunk 2]
```diff
@@ -97,12 +98,14 @@ class FileDetailsFragment : FileDetailsSubFragment() {
 
     private fun setNoPreviewIcon(file: File) {
         val fileType = file.getFileType()
-        val icon = if (fileType == ConvertedType.FOLDER) {
-            file.getFolderIcon(requireContext())
-        } else {
-            ContextCompat.getDrawable(requireContext(), fileType.icon)
+
+        noPreviewLayout.icon.apply {
+            val (icon, tint) = file.getFolderIcon()
```
Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt:103]: We get the folderIcon even before checking if it is a folder

**Review by JorisBodin — CHANGES_REQUESTED** [review]

**Review by JorisBodin — APPROVED** [review]

**Review by sirambd — APPROVED** [review]
