### PR TITLE
Fix collapsing toolbar threshold

### LINKED ISSUE #622: Remove "EXPAND_TITLE_THRESHOLD"

### PR DESCRIPTION
**Pull request by FabianDevel**
closes  #622

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt [hunk 1]
```diff
@@ -129,14 +115,28 @@ class FileDetailsFragment : FileDetailsSubFragment() {
     }
 
     private fun setBannerThumbnail(file: File) {
+        val params = subtitleToolbar.layoutParams as CoordinatorLayout.LayoutParams
+        val collapsingToolbarBehavior = params.behavior as? CollapsingSubTitleToolbarBehavior
+
+        appBar.addOnOffsetChangedListener(object : AppBarStateChangeListener() {
+            override fun onStateChanged(appBarLayout: AppBarLayout?, state: State?) {
+                collapsingToolbarBehavior?.let {
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt:123]: `apply` instead of `let`

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt [hunk 2]
```diff
@@ -174,4 +174,27 @@ class FileDetailsFragment : FileDetailsSubFragment() {
...
+        override fun onOffsetChanged(appBarLayout: AppBarLayout, yOffset: Int) {
+            // ScrimVisibleHeightTrigger starts from the top of the appbar and stops at the collapsing threshold
+            val appBarCollapsingThreshold =
+                appBarLayout.height - appBarLayout.fileDetailsCollapsingToolbar.scrimVisibleHeightTrigger
+
+            currentState = if (abs(yOffset) <= appBarCollapsingThreshold) {
+                callStateChangeListener(appBarLayout, State.EXPANDED)
+            } else {
+                callStateChangeListener(appBarLayout, State.COLLAPSED)
+            }
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt:191]:
```suggestion
            currentState = callStateChangeListener(
                appBarLayout = appBarLayout,
                state = if (abs(yOffset) <= appBarCollapsingThreshold) State.EXPANDED else State.COLLAPSED,
            )
```

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt [hunk 3]
```diff
@@ -129,14 +115,28 @@ class FileDetailsFragment : FileDetailsSubFragment() {
...
 
     private fun setBannerThumbnail(file: File) {
+        val params = subtitleToolbar.layoutParams as CoordinatorLayout.LayoutParams
+        val collapsingToolbarBehavior = params.behavior as? CollapsingSubTitleToolbarBehavior
+
+        appBar.addOnOffsetChangedListener(object : AppBarStateChangeListener() {
+            override fun onStateChanged(appBarLayout: AppBarLayout?, state: State?) {
+                collapsingToolbarBehavior?.let {
+                    it.isNewState = true
+                    it.isExpanded = state == State.EXPANDED
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt:125]:
```suggestion
                collapsingToolbarBehavior?.apply {
                    isNewState = true
                    isExpanded = state == State.EXPANDED
```

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt [hunk 4]
```diff
@@ -129,14 +115,28 @@ class FileDetailsFragment : FileDetailsSubFragment() {
...
+
+                    // If in Light mode, change the status icons color to match the background.
+                    // If in Dark mode, the icons stay white all along, no need to check.
+                    if (context?.resources?.isNightModeEnabled() == false) activity?.window?.lightStatusBar(!it.isExpanded)
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt:129]:
```suggestion
                collapsingToolbarBehavior?.apply {
                    isNewState = true
                    isExpanded = state == State.EXPANDED

                    // If in Light mode, change the status icons color to match the background.
                    // If in Dark mode, the icons stay white all along, no need to check.
                    if (context?.resources?.isNightModeEnabled() == false) activity?.window?.lightStatusBar(!isExpanded)
```

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt (hunk 2 above)
Comment (FabianDevel) [reply app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt]: done

File: app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt (hunk 4 above)
Comment (FabianDevel) [reply app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt]: done

**Review by KevinBoulongne — APPROVED** [review]

**Review by JorisBodin — APPROVED** [review]
