### PR TITLE
Fixed Categories rights in Shared folders

### LINKED ISSUE #456: We can add Categories to a SharedFolder, even if we don't have the rights to do it

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #456

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt [hunk 1]
```diff
@@ -63,24 +65,32 @@ class CategoriesContainerView @JvmOverloads constructor(
...
+        layoutInflater: LayoutInflater,
+        onClicked: () -> Unit,
+    ) = with(categoriesGroup) {
+        if (categories.isNotEmpty()) {
+            isVisible = true
+            removeAllViews()
+            categories.forEach { addView(createChip(canPutCategoryOnFile, it, layoutInflater, onClicked)) }
+        } else {
+            isGone = true
         }
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt:80]: I think it's better to invert this if condion

**Review by JorisBodin — APPROVED** [review]

**Review by sirambd — APPROVED** [review]
