### PR TITLE
Fixed FolderCreation button not clickable when the view is recreated

### LINKED ISSUE #438: In the folder creation view, when the view is recreated, the `Create folder` button is no longer clickable

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #438

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt [hunk 1]
```diff
@@ -18,6 +18,7 @@
 package com.infomaniak.drive.ui.addFiles
 
 import android.os.Bundle
+import android.util.Log
```
Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt:21]: Unused import

File: app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt [hunk 2]
```diff
@@ -65,7 +65,7 @@ class CreateCommonFolderFragment : CreateFolderFragment() {
 
         newFolderViewModel.createCommonFolder(
             name = folderNameValueInput.text.toString(),
-            forAllUsers = currentPermission == ALL_DRIVE_USERS,
+            forAllUsers = newFolderViewModel.currentPermission == ALL_DRIVE_USERS,
```
Comment (JorisBodin) [inline app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt:68]: Why set the value if it is already in newFolderViewModel?

**Review by JorisBodin — CHANGES_REQUESTED** [review]

**Review by JorisBodin — APPROVED** [review]
