### PR TITLE
Fixed navigation issue when creating a Dropbox or Common folder

### LINKED ISSUE #439: Since 4.1, the creation of Dropbox & Common folders with the option `Some users` doesn't work as before

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #439

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt [hunk 1]
```diff
@@ -184,9 +184,18 @@ object DriveInfosController {
...
 
-    private fun getCurrentDrive(realm: Realm): Drive? {
-        return realm.where(Drive::class.java)
-            .equalTo(Drive::id.name, AccountUtils.currentDriveId)
-            .findFirst()
+    fun getCurrentDriveId(): Int? {
+        return getRealmInstance().use { realm ->
+            getCurrentDrive(realm)?.id
+        }
+    }
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt:191]: No need, we already have `AccountUtils.currentDriveId`

**Comment by sirambd** [comment]
I refactored [CreateCommonFolderFragment](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-eb9e102ab58e1ced602ae2f601fe5ea107852a274872d7f28ad656a176f1e127) cleanly so that we can understand it better, and I removed what was unnecessary.

**Comment by sirambd** [comment]
> 



> I refactored [CreateCommonFolderFragment](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-eb9e102ab58e1ced602ae2f601fe5ea107852a274872d7f28ad656a176f1e127) cleanly so that we can understand it better, and I removed what was unnecessary.
> 
> commit: [76a96f8](https://github.com/Infomaniak/android-kDrive/commit/76a96f889e985c6ea8e55c3fef1bb2e01eae1b24)

Can you continue refactor with [CreateDropBoxFolderFragment.kt](https://github.com/Infomaniak/android-kDrive/pull/446/files#diff-6e5dc698bc40dca50876442861058f194585b454f313de05bdfe87ca62c01bda) ?

File: app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt [hunk 2]
```diff
@@ -33,6 +35,9 @@ import com.infomaniak.lib.core.models.ApiResponse
 import kotlinx.android.synthetic.main.empty_icon_layout.view.*
 import kotlinx.android.synthetic.main.fragment_create_folder.*
 import kotlinx.android.synthetic.main.item_dropbox_settings.*
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.launch
+import kotlinx.coroutines.withContext
 import okhttp3.internal.toLongOrDefault
 
 class CreateDropBoxFolderFragment : CreateFolderFragment() {
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt:43]: Need refactor

File: app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt [hunk 3]
```diff
@@ -67,11 +72,20 @@ class CreateDropBoxFolderFragment : CreateFolderFragment() {
...
                     findNavController().popBackStack(R.id.newFolderFragment, true)
                 } else {
-                    safeNavigate(
-                        CreateDropBoxFolderFragmentDirections.actionCreateDropBoxFolderFragmentToFileShareDetailsFragment(
-                            fileId = file.id, ignoreCreateFolderStack = true
-                        )
-                    )
+                    lifecycleScope.launch(Dispatchers.IO) {
+
+                        FileController.addFileTo(newFolderViewModel.currentFolderId.value!!, file)
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt:77]: It's better to have this in the `ViewModel`, it will allow you to avoid `Dispatchers` and `isResume`

**Review by sirambd — CHANGES_REQUESTED** [review]
Waiting feedback fix

**Review by JorisBodin — APPROVED** [review]

**Review by sirambd — APPROVED** [review]
