### PR TITLE
Fixed Dropbox ShareLink UI

### LINKED ISSUE #444: The wrong ShareLink UI is displayed for Dropboxes

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Signed-off-by: Kevin Boulongne <kevin.boulongne@infomaniak.com>

Closes #444

### CODE REVIEW

File: app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt [hunk 1]
```diff
@@ -45,44 +45,79 @@ class ShareLinkContainerView @JvmOverloads constructor(
...
+        onTitleClicked: ((shareLink: ShareLink?, currentFileId: Int) -> Unit)? = null,
+        onSettingsClicked: ((shareLink: ShareLink, currentFile: File) -> Unit)? = null,
     ) {
         currentFile = file
         this.shareLink = shareLink
         isVisible = true
         urlValue = file.shareLink ?: ""
 
-        updateUi()
+        selectUI(file.isDropBox())
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt:56]: I think that a comment, it'll be better, just say for example `Hide this component for dropbox folder` 🤔, or a method that is more meaningful

File: app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt [hunk 2]
```diff
@@ -45,44 +45,79 @@ class ShareLinkContainerView @JvmOverloads constructor(
...
 
-        titleContainer.setOnClickListener { onTitleClicked(this.shareLink, currentFile.id) }
-        // cannot be null, if null, settings will not appear
-        shareLinkSettings.setOnClickListener { onSettingsClicked(this.shareLink!!, currentFile) }
+        if (file.isDropBox()) return
 
+        titleContainer.setOnClickListener { onTitleClicked?.invoke(this.shareLink, currentFile.id) }
+        // cannot be null, if null, settings will not appear
+        shareLinkSettings.setOnClickListener { onSettingsClicked?.invoke(this.shareLink!!, currentFile) }
         shareLinkButton.setOnClickListener { this.shareLink?.url?.let(context::shareText) }
```
Comment (sirambd) [inline app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt:63]: I think that'll be good without the return here, 
You need make this if only it's not a dropBox

**Review by sirambd — CHANGES_REQUESTED** [review]
Waiting fix feedback

**Review by sirambd — APPROVED** [review]
